### ISSUE TITLE
ARMv7 version ?

### ISSUE THREAD

**Issue by 1300371** [barasher/influxdb-pusher#3]
Hello, is that possible to release a version ARMv7 of `pusher` ? 
I try to automate your project in a Pi :)

Nice project btw !

**Comment by barasher** [comment]
Hi.
I'm using influxdb-pusher on a raspberry pi using this release : https://github.com/barasher/influxdb-pusher/releases/download/v1.1/pusher_v1.1_linux_arm
I unfortunately don't remember which arm version this binary has been compiled for (I should have associated this information with the filename...) but since I'm personnaly using it on an armv7 raspberry pi, it should also be ok for you.
I'll recompile the binary and specify the arm version on the filename but I'm unfortunately unable to do it right now, I'm on vacation, without computer. I'll only be able to do it after the 15th of July.
Until then, use the https://github.com/barasher/influxdb-pusher/releases/download/v1.1/pusher_v1.1_linux_arm version and tell me if you have any problem.

**Comment by 1300371** [comment]
OK ! My bad ... 
I just checked my Dockerfile
```
RUN wget -q -O pusher https://github.com/barasher/influxdb-pusher/releases/download/v1.1/pusher_v1.1_linux_386
```
I used the _i386_ version :(

Enjoy your holidays !!

**Comment by 1300371** [comment]
Seems to work with the good binary ... but as usual the Enedis website is down XD
Thanks for your support

**Comment by barasher** [comment]
Enedis has a maintenance downtime every night around 23:00 Paris time.
I crawl my personnal daily data around 20:00 Paris time (using https://github.com/barasher/linky-to-influxdb that itself uses infludb-pusher).
There is perhaps 1 or 2 failure per month, I have a recover procedure to deal with these situations.

**Comment by barasher** [comment]
@1300371 > Here is the "official" ARM v7 release : https://github.com/barasher/influxdb-pusher/releases/download/v1.1/pusher_v1.1_linux_arm_7
